### PR TITLE
Resubmission finish mobile

### PR DESCRIPTION
**Pull request by the-faizmohammad**
For the initial milestone in the process of creating a portfolio website, I have completed the following steps:

Implemented different sections: header , headline, work, about me. These sections are essential components of the website's structure.

Configured the Linter for this repository to ensure proper code formatting and adherence to coding standards.

Created a descriptive README file that provides an overview of the project, its purpose, and instructions on how to set it up and run it.
Created a new branch according to the GitHub flow rules.
Updated the index.html file to include a work section, an about page, and a contact page.
Added CSS styles in the style.css file for the work, about me and others.

Submitted a Pull Request from the 'feature branch' to the main branch, allowing for code review and integration of the implemented changes into the main codebase.

Utilized HTML and CSS languages to develop the website, ensuring proper markup and styling for optimal presentation and user experience.

These accomplishments mark the initial progress in the creation of the portfolio website, setting a solid foundation for future development and enhancements.

### CODE REVIEW

**Review by bellom — APPROVED** [review]
@the-faizmohammad, 

### This is a manual review

You can still improve this section (About page):
- broken image 
- get my resume button
image

Because you only have some issues with the About page, I will go ahead and approve this PR, it would be nice to make the necessary changes before merging.

# Approved :+1:

Cheers and Happy coding!:clap::clap::clap:

**Comment by the-faizmohammad** [comment]
It working fine in my virtual machine.

**Comment by the-faizmohammad** [comment]
It working fine in my virtual machine.

**Comment by bellom** [comment]
@the-faizmohammad - I'm afraid not, yes, it will work on local cause of the relative path.

Test with this - https://raw.githack.com/the-faizmohammad/my-portfolio/resubmission-finish-mobile/index.html

You have used the wrong name `Javascript` instead of using `javascript`

image

**Pull request merged**
